---
title: "p8105_hw2_lcc2181"
output: github_document
---

## Problem 1

```{r, echo=FALSE, message=FALSE}
library(tidyverse)
library(readxl)
```

Reading and cleaning the Mr. Trash Wheel sheet.

```{r}
trash_wheel_df = 
  read_excel("data/Trash-Wheel-Collection-Totals-8-6-19.xlsx", 
  sheet = "Mr. Trash Wheel", 
  range = "A2:N408") %>%
  janitor::clean_names() %>% 
  drop_na(dumpster) %>% 
  mutate(sports_balls = round(sports_balls, digits = 0))
```

Reading and cleaning precipitation data for 2018.

```{r}
precip_2018_df = 
  read_excel ("data/Trash-Wheel-Collection-Totals-8-6-19.xlsx",
             sheet = "2018 Precipitation",
             range = "A2:B15") %>% 
  janitor::clean_names() %>% 
  drop_na(total) %>% 
  mutate(year ="2018")
                 
```

Reading and cleaning precipitation data for 2019.

```{r}
precip_2019_df = 
  read_excel ("data/Trash-Wheel-Collection-Totals-8-6-19.xlsx",
             sheet = "2019 Precipitation",
             range = "A2:B15") %>% 
  janitor::clean_names() %>% 
  drop_na(total) %>% 
  mutate(year ="2019")
```

